name: Tvheadend Github "action" workflows

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - run: sudo ./Autobuild.sh -t bionic-amd64 -o deps
      - run: ./Autobuild.sh -t bionic-amd64
      
